name: deployment
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: chache Dependencies
        uses: action/chache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: print node version
        run: node -v
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm run test 
